# Generated by Django 4.0.3 on 2022-03-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fragmentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fragmentos',
            new_name='Fragmento',
        ),
    ]
